spring:
  config:
    activate:
      on-profile: "qa"

build:
  version: 2.0

accounts:
  message: "Welcome to Zeroo8 qa section"
  contactDetails:
    name: Mayesha
    email: reactive.sys@gmail.com
  onCallSupport:
    -(453)3435
    -(444)3456